#!/usr/bin/env bash

g++ -E -Dinclude='#include' -I. -I"$(dirname $0)/include/system-dummy" "$1" | grep -v '^# [0-9]' | sed -E 's/^ #include/#include/g' | ruby -e 'puts STDIN.read.gsub(/\n{3,}/m, "\n")'
